---
- hosts: all
  # become_method: sudo
  # become_user: root
  sudo: true
  remote_user: felix
  # gather_facts: no
  pre_tasks:
    # - raw: sudo apt-get install python-simplejson
  vars:
    rbenv:
      env: user
      version: v0.4.0
      ruby_version: 2.2.3
  roles:
    - role: common
    - role: docker
